### ISSUE TITLE
Endpoint rate limiting doesn't work with signer extra config

### ISSUE THREAD

**Issue by suadev** [devopsfaith/krakend-ratelimit#15]
I have an endpoint to sign jwt token  ->  http://localhost:5000/identity-api/sign-in

I also want to throttle this endpoint like below, but it doesn't work.

If I delete the signer extra config, rate-limiting just works. Seems like they both don't work together?

````       
 "extra_config": {
                "github.com/devopsfaith/krakend-jose/signer": {
                    "alg": "HS256",
                    "kid": "sim1",
                    "keys-to-sign": [
                        "access_token"
                    ],
                    "jwk-url": "http://file_server:8080/jwk/symmetric.json",
                    "disable_jwk_security": true
                },
                "github.com/devopsfaith/krakend-ratelimit/juju/router": {
                    "maxRate": 1,
                    "clientMaxRate": 1,
                    "strategy": "ip"
                }
            }

````

**Comment by kpacha** [comment]
when enabled, the signer handler ignores the injected handler factory and talks directly to the proxy layer (in order to avoid an extra decoding and encoding of the response).

you can split the functionality in 2 handlers:
a) one dealing with the rate-limiting (the public)
b) another dealing with the signing (with a more obscure path)

your clients will request the token to endpoint A and it will internally call to endpoint B

cheers!
